/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EducationProvider.AssignVolunteer;

import Business.Class.Course;
import Business.Classroom.Classroom;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EducationProvider.AssignVolunteerOrganization;
import Business.Organization.Organization;

import Business.Person.Volunteer;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VolunteerRequest.VolunteerRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lintong
 */

//回应FBPI
public class AssignVolunteer extends javax.swing.JPanel {

    /**
     * Creates new form AssignVolunteer
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private AssignVolunteerOrganization assignVolunteerOrganzation;
    private EcoSystem system;
    public AssignVolunteer(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.account = account;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.assignVolunteerOrganzation = (AssignVolunteerOrganization)organization;
        this.system=system;
        populateVolunteerTable();
        populateCourseTable();
        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CourseTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        VolunteerTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        SearchBtn = new javax.swing.JButton();

        CourseTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ClassID", "Weekday", "Description", "StartDay", "EndDay", "Sender", "Reciever", "Status", "VolunteerID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CourseTbl);
        if (CourseTbl.getColumnModel().getColumnCount() > 0) {
            CourseTbl.getColumnModel().getColumn(0).setResizable(false);
            CourseTbl.getColumnModel().getColumn(1).setResizable(false);
            CourseTbl.getColumnModel().getColumn(2).setResizable(false);
            CourseTbl.getColumnModel().getColumn(3).setResizable(false);
            CourseTbl.getColumnModel().getColumn(4).setResizable(false);
            CourseTbl.getColumnModel().getColumn(5).setResizable(false);
            CourseTbl.getColumnModel().getColumn(6).setResizable(false);
            CourseTbl.getColumnModel().getColumn(7).setResizable(false);
            CourseTbl.getColumnModel().getColumn(8).setResizable(false);
        }

        VolunteerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "VolunteerID", "Name", "Available Time", "AvailableWeekday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(VolunteerTbl);
        if (VolunteerTbl.getColumnModel().getColumnCount() > 0) {
            VolunteerTbl.getColumnModel().getColumn(0).setResizable(false);
            VolunteerTbl.getColumnModel().getColumn(1).setResizable(false);
            VolunteerTbl.getColumnModel().getColumn(2).setResizable(false);
            VolunteerTbl.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Assign");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("MM/dd/yyyy");

        jLabel2.setText("Available Start ");

        jLabel3.setText("Available End");

        jDateChooser2.setDateFormatString("MM/dd/yyyy");

        SearchBtn.setText("Serach");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(469, 469, 469)
                                    .addComponent(jButton1)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(SearchBtn)))
                .addGap(0, 108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SearchBtn))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow1 = VolunteerTbl.getSelectedRow();
        if (selectedRow1 < 0){
            return;
        }  
        Volunteer volunteer = (Volunteer)VolunteerTbl.getValueAt(selectedRow1, 0);
        
        int selectedRow2 = CourseTbl.getSelectedRow();
        if (selectedRow2 < 0){
            return;
        }  
        VolunteerRequest vr = (VolunteerRequest)CourseTbl.getValueAt(selectedRow2, 0);  
        vr.setVolunteer(volunteer);
        vr.getCourseRequest().setVolunteer(volunteer);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void populateVolunteerTable(){
        DefaultTableModel model = (DefaultTableModel) VolunteerTbl.getModel();
        
        model.setRowCount(0);
        for(Volunteer volunteer:assignVolunteerOrganzation.getVolunteerDirectory().getVolunteerDirectory()){
            Object[] row = new Object[4];
            row[0] = volunteer.getPersonID();
            row[1] = volunteer;
            row[2] = volunteer.getTimeTable();
            row[3] = volunteer.getAvailableWeekday();
            
         
            model.addRow(row);
        }
    }
    public void populateCourseTable(){
        DefaultTableModel model = (DefaultTableModel) VolunteerTbl.getModel();
        
        model.setRowCount(0);
        
        for(VolunteerRequest vr:(ArrayList<VolunteerRequest>) assignVolunteerOrganzation.getWorkQueue().getWorkRequestMap().get(WorkRequest.Type.VolunteerRequest)){
            Object[] row = new Object[6];
            row[0]=vr.getCourse().getID();
            row[1]=vr.getCourse().getWeekDay();
            row[2]=vr.getCourse().getDescription();
            row[3]=vr.getCourse().getStartDate();
            row[4]=vr.getCourse().getEndDate();
            row[5]=vr.getSender();
            row[6]=vr.getReciever();
            row[7]=vr.getStatus();
            row[8]=vr.getVolunteer().getPersonID();
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CourseTbl;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTable VolunteerTbl;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
