/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EducationProvider.HR;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EducationProvider.VolunteerHROrganization;
import Business.Organization.Organization;
import Business.Person.Volunteer;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lintong
 */


//增删volunteer
public class EducationProviderHR extends javax.swing.JPanel {

    /**
     * Creates new form EducationProviderHR
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private VolunteerHROrganization volunteerHROrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    public EducationProviderHR(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.enterprise = enterprise;
        this.account = account;
        this.volunteerHROrganization = (VolunteerHROrganization)organization;
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        populateVolunteerTable();//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VolunteerTbl = new javax.swing.JTable();
        CreateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userAccountTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();

        VolunteerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "VolunteerID", "Name", "User Account"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VolunteerTbl);
        if (VolunteerTbl.getColumnModel().getColumnCount() > 0) {
            VolunteerTbl.getColumnModel().getColumn(0).setResizable(false);
            VolunteerTbl.getColumnModel().getColumn(1).setResizable(false);
            VolunteerTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("UserAccount");

        userAccountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAccountTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CreateBtn)
                        .addGap(34, 34, 34)
                        .addComponent(DeleteBtn)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameTxt)
                            .addComponent(userAccountTxt)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userAccountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void populateVolunteerTable(){
         
        DefaultTableModel model = (DefaultTableModel) VolunteerTbl.getModel();
        
        model.setRowCount(0);
        
        for (Volunteer vt :volunteerHROrganization.getVolunteerDirectory().getVolunteerDirectory()){
            Object[] row = new Object[3];
            row[0] = vt;
            row[1] = vt.getFirstname();
            row[2] = vt.getUserAccount().getUsername();
         
            model.addRow(row);
        }
    }
            
    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        Volunteer vt = volunteerHROrganization.getVolunteerDirectory().addVolunteer();
        vt.setFirstname(NameTxt.getText());
        vt.getUserAccount().setUsername(userAccountTxt.getText());
        vt.getUserAccount().setPassword(passwordTxt.getText());
        JOptionPane.showMessageDialog(null,"Volunteer Created Successfully");// TODO add your handling code here:
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void userAccountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAccountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAccountTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int selectedRow = VolunteerTbl.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        Volunteer vt = (Volunteer)VolunteerTbl.getValueAt(selectedRow, 0);  
        volunteerHROrganization.getVolunteerDirectory().deleteVolunteer(vt);// TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTable VolunteerTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField userAccountTxt;
    // End of variables declaration//GEN-END:variables
}
