/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EducationProvider.ManageCenter;

import Business.Class.Course;
import Business.Classroom.Classroom;
import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Organization.EducationProvider.ManageCenterOrganization;
import Business.Organization.EducationProvider.VolunteerHROrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VolunteerRequest.VolunteerRequest;
import Business.WorkQueue.VolunteerRequest.VolunteerRequestHistory;
import Business.WorkQueue.WorkRequest;
import Business.WorkRequest.ClassroomRequest.ClassroomRequest;
import Business.WorkRequest.ClassroomRequest.ClassroomRequestHistory;
import Business.WorkRequest.courseRequest.CourseRequest;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lintong
 */
public class ManageCenter extends javax.swing.JPanel {

    /**
     * Creates new form ManageCenter
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    
    private ManageCenterOrganization manageCenterOrganization;
    private Enterprise enterprise;
    private EcoSystem system;

    public ManageCenter(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.enterprise = enterprise;
        this.account = account;
        this.manageCenterOrganization = (ManageCenterOrganization)organization;
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        populateCourseTable();//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CourseRequestTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        VolunteerBtn = new javax.swing.JButton();
        ClassroomBtn = new javax.swing.JButton();

        CourseRequestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ClassID", "Weekday", "Description", "StartDay", "EndDay", "Sender", "Reciever", "Status", "VolunteerID", "ClassroomID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CourseRequestTbl);
        if (CourseRequestTbl.getColumnModel().getColumnCount() > 0) {
            CourseRequestTbl.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Manage Center");

        VolunteerBtn.setText("Send Volunteer Request");
        VolunteerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolunteerBtnActionPerformed(evt);
            }
        });

        ClassroomBtn.setText("Send Classroom Request");
        ClassroomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassroomBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ClassroomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VolunteerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(VolunteerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClassroomBtn)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VolunteerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerBtnActionPerformed
        int selectedRow = CourseRequestTbl.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        CourseRequest cr = (CourseRequest)CourseRequestTbl.getValueAt(selectedRow, 0);  
        Course course = cr.getCourse();
        VolunteerRequestHistory volunteerRequestHistory = manageCenterOrganization.getVolunteerRequestHistory();
        VolunteerRequest vr = volunteerRequestHistory.addVolunteerRequest();
        vr.setCourse(course);
        vr.setSender(account);
        vr.setCourseRequest(cr);// TODO add your handling code here:
    }//GEN-LAST:event_VolunteerBtnActionPerformed

    private void ClassroomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassroomBtnActionPerformed
        int selectedRow = CourseRequestTbl.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        CourseRequest cr = (CourseRequest)CourseRequestTbl.getValueAt(selectedRow, 0);  
        Course course = cr.getCourse();
        ClassroomRequestHistory classroomRequestHistory = manageCenterOrganization.getClassroomRequestHistory();
        ClassroomRequest classroomRequest = classroomRequestHistory.addClassroomRequest();
        
        classroomRequest.setCourse(course);
        classroomRequest.setSender(account);
        classroomRequest.setCourseRequest(cr);// TODO add your handling code here:
    }//GEN-LAST:event_ClassroomBtnActionPerformed

    public void populateCourseTable(){
        DefaultTableModel model = (DefaultTableModel) CourseRequestTbl.getModel();
        
        model.setRowCount(0);
        
        for(CourseRequest cr:(ArrayList<CourseRequest>) manageCenterOrganization.getWorkQueue().getWorkRequestMap().get(WorkRequest.Type.CourseRequest)){
            Object[] row = new Object[6];
            row[0]=cr.getCourse().getID();
            row[1]=cr.getCourse().getWeekDay();
            row[2]=cr.getCourse().getDescription();
            row[3]=cr.getCourse().getStartDate();
            row[4]=cr.getCourse().getEndDate();
            row[5]=cr.getSender();
            row[6]=cr.getReciever();
            row[7]=cr.getStatus();
            row[8]=cr.getVolunteer().getPersonID();
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClassroomBtn;
    private javax.swing.JTable CourseRequestTbl;
    private javax.swing.JButton VolunteerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
