/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sponsor;

import Business.Classroom.Classroom;
import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.Sponsor.SponsorAdvertisingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkRequest.ClassroomRequest.ClassroomRequest;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lintong
 */
public class Advertising extends javax.swing.JPanel {

    /**
     * Creates new form Adversing
     */
    
        

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private SponsorAdvertisingOrganization sponsorAdvertisingOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    public Advertising(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.enterprise=enterprise;
        this.sponsorAdvertisingOrganization = (SponsorAdvertisingOrganization)organization;
        this.system=system;
        populateClassroomTable();
        populateClassTable();//To change body of generated methods, choose Tools | Templates.
    }
    
    public ArrayList<Classroom> filterClassroom(){
        ArrayList<Classroom>  temlist= new ArrayList<Classroom>();
        for(Classroom classroom:sponsorAdvertisingOrganization.getClassroomList().getClassroomList()){
            if (classroom.getSponsorName().equals(enterprise.getName())){
                temlist.add(classroom);
            }
        }
        return temlist;
    }
    
    public void populateClassroomTable(){
    DefaultTableModel model = (DefaultTableModel) ClassroomTbl.getModel();
        
        model.setRowCount(0);
        ArrayList<Classroom> filterList=filterClassroom();
        for(Classroom classroom:filterList){
            Object[] row = new Object[6];
            row[0] = classroom.getID();
            row[1] = classroom;
            row[2] = classroom.getAccomodation();
            row[3] = classroom.getAvailWeekday();
            row[4] = classroom.getAvailStart();
            row[5] = classroom.getAvailEnd();
            
         
            model.addRow(row);
        }
    }
    
     public void populateClassTable(){
        
        DefaultTableModel model = (DefaultTableModel) classroomRequestTbl.getModel();
        
        model.setRowCount(0);
        for (ClassroomRequest request :(ArrayList<ClassroomRequest>) organization.getWorkQueue().getWorkRequestMap().get(WorkRequest.Type.ClassroomRequest)){
            Object[] row = new Object[6];
            row[0] = request.getCourse().getID();
            row[1] = request.getClassroom().getID();
            row[2] = request.getPublishDate();
            row[3] = request.getSender();
            row[4] = request.getReciever();
            row[5] = request.getClassroom().getAccomodation();
         
            model.addRow(row);
        }
        
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        classroomRequestTbl = new javax.swing.JTable();
        AssignBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClassroomTbl = new javax.swing.JTable();

        classroomRequestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ClassID", "ClassRoomID", "Date", "Sender", "Reciever", "accomodation", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classroomRequestTbl);
        if (classroomRequestTbl.getColumnModel().getColumnCount() > 0) {
            classroomRequestTbl.getColumnModel().getColumn(0).setResizable(false);
            classroomRequestTbl.getColumnModel().getColumn(1).setResizable(false);
            classroomRequestTbl.getColumnModel().getColumn(2).setResizable(false);
            classroomRequestTbl.getColumnModel().getColumn(3).setResizable(false);
            classroomRequestTbl.getColumnModel().getColumn(4).setResizable(false);
            classroomRequestTbl.getColumnModel().getColumn(5).setResizable(false);
            classroomRequestTbl.getColumnModel().getColumn(6).setResizable(false);
        }

        AssignBtn.setText("Assign");
        AssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignBtnActionPerformed(evt);
            }
        });

        ClassroomTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ClassroomID", "ClassroomNum", "Accomdation", "AvailWeekDay", "AvailDayStart", "AvailDayEnd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ClassroomTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AssignBtn)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(AssignBtn)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        int selectedRow1 = ClassroomTbl.getSelectedRow();
        
        if (selectedRow1 < 0){
            return;
        }
        
        Classroom classroom = (Classroom)ClassroomTbl.getValueAt(selectedRow1, 0); 
        
        int selectedRow2 = classroomRequestTbl.getSelectedRow();
        
        if (selectedRow2 < 0){
            return;
        }
        
        ClassroomRequest classroomRequest = (ClassroomRequest)classroomRequestTbl.getValueAt(selectedRow2, 0); 
        classroomRequest.setClassroom(classroom);
        classroomRequest.setReciever(account);
        classroomRequest.setStatus("Authorized");
        classroomRequest.getCourseRequest().setClassroom(classroom);
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignBtn;
    private javax.swing.JTable ClassroomTbl;
    private javax.swing.JTable classroomRequestTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
